const {
  withAppBuildGradle,
  withDangerousMod,
  withMainApplication,
} = require("@expo/config-plugins")
const fs = require("fs")
const path = require("path")

const RFID_SOURCE_FILES = [
  "CallbackHandler.java",
  "KeyEventModule.java",
  "KeyPackage.java",
  "RfidException.java",
  "RfidInitializationException.java",
  "RfidManager.java",
  "RfidOperationException.java",
  "ScanningService.java",
  "UHFModule.java",
  "UHFPackage.java",
]

const RFID_JARS = [
  "DeviceAPIver20150204.jar",
  "ModuleAPI_J.jar",
  "SerialPort.jar",
  "UHF67_v1.0.9.jar",
  "reader(1).jar",
]

const RFID_DEPENDENCIES = `    // @generated by withRfidScanner
    implementation 'io.reactivex.rxjava3:rxjava:3.1.5'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation files('libs/DeviceAPIver20150204.jar')
    implementation files('libs/ModuleAPI_J.jar')
    implementation files('libs/SerialPort.jar')
    implementation files('libs/UHF67_v1.0.9.jar')
    implementation files('libs/reader(1).jar')
`

/**
 * Expo config plugin for the handheld UHF reader.
 *
 * The vendor SDK is kept under android-backup so `expo prebuild --clean` cannot
 * delete the only copy. This plugin copies the required sources and binaries
 * into the generated Android project and registers the two legacy RN packages.
 */
function withRfidScanner(config) {
  config = withAppBuildGradle(config, (config) => {
    const gradle = config.modResults.contents
    if (!gradle.includes("// @generated by withRfidScanner")) {
      config.modResults.contents = gradle.replace(
        /dependencies\s*\{/,
        `dependencies {\n${RFID_DEPENDENCIES}`,
      )
    }
    return config
  })

  config = withMainApplication(config, (config) => {
    let source = config.modResults.contents

    if (!source.includes("import com.herdtrackr.rfid.UHFPackage")) {
      source = source.replace(
        /package com\.herdtrackr\s*/,
        `package com.herdtrackr\n\nimport com.herdtrackr.rfid.KeyPackage\nimport com.herdtrackr.rfid.UHFPackage\n`,
      )
    }

    if (!source.includes("add(UHFPackage())")) {
      source = source.replace(
        /(PackageList\(this\)\.packages\.apply\s*\{)/,
        `$1\n              // Handheld UHF RFID reader\n              add(UHFPackage())\n              add(KeyPackage())`,
      )
    }

    config.modResults.contents = source
    return config
  })

  return withDangerousMod(config, [
    "android",
    async (config) => {
      const projectRoot = config.modRequest.projectRoot
      const vendorRoot = path.join(projectRoot, "android-backup", "app")
      const androidApp = path.join(config.modRequest.platformProjectRoot, "app")
      const sourceRoot = path.join(vendorRoot, "src", "main", "java", "com", "herdtrackr", "rfid")
      const sourceTarget = path.join(androidApp, "src", "main", "java", "com", "herdtrackr", "rfid")
      const libsTarget = path.join(androidApp, "libs")
      const nativeSource = path.join(vendorRoot, "src", "main", "jniLibs")
      const nativeTarget = path.join(androidApp, "src", "main", "jniLibs")

      for (const requiredPath of [sourceRoot, nativeSource]) {
        if (!fs.existsSync(requiredPath)) {
          throw new Error(`RFID vendor source is missing: ${requiredPath}`)
        }
      }

      fs.mkdirSync(sourceTarget, { recursive: true })
      fs.mkdirSync(libsTarget, { recursive: true })

      for (const file of RFID_SOURCE_FILES) {
        fs.copyFileSync(path.join(sourceRoot, file), path.join(sourceTarget, file))
      }
      for (const file of RFID_JARS) {
        fs.copyFileSync(path.join(vendorRoot, "libs", file), path.join(libsTarget, file))
      }
      fs.cpSync(nativeSource, nativeTarget, { recursive: true })

      return config
    },
  ])
}

module.exports = withRfidScanner
